export const XP_EVENTS = {
  WORKOUT_COMPLETE: 50,
  STREAK_BONUS_PER_DAY: 10,
  PERSONAL_RECORD: 25,
  PROGRAM_DAY_COMPLETE: 15,
  PROGRAM_COMPLETE: 200,
  FIRST_WORKOUT: 100,
  PROFILE_COMPLETE: 50,
} as const;

export type XpEventType = keyof typeof XP_EVENTS;

export const MIN_WORKOUT_DURATION_SECONDS = 15 * 60;

export const LEADERBOARD_MIN_MEMBERS = 5;
